[package]
name = "tldr-patch"
version = "0.1.0"
authors = ["Chris Hamons <chris.hamons@microsoft.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
error-chain = "0.12.4"
clap = "3.0.0-beta.2"
regex = "1"